### ISSUE TITLE
Missing L2TP kernel modules

### ISSUE THREAD

**Issue by bennlich** [sudomesh/tunneldigger-lab#3]
I tried to tunnel to exit.sudomesh.org:8942, but it looks like I'm missing some kernel modules?

```
toyfish@ubuntown:~$ sudo cat /var/log/syslog | grep td-client
Feb  6 08:25:31 ubuntown td-client: Failed to resolve L2TP netlink interface - check if L2TP kernel modules are loaded!
Feb  6 08:25:31 ubuntown td-client: Unable to initialize tunneldigger context! Retrying in 5 seconds...
```

I'm on a fresh Ubuntu 16.04.3 LTS droplet 4.4.0-112-generic, running master branch from https://github.com/wlanslovenija/tunneldigger.

**Comment by jhpoelen** [comment]
@bennlich yes! I actually just hit that same issue last night. @Juul reminded me of the kernel module dependencies. I've updated readme to make this explicit. Better now?

**Comment by bennlich** [comment]
@jhpoelen:
```
toyfish@ubuntown:~$ sudo modprobe l2tp_eth
modprobe: FATAL: Module l2tp_eth not found in directory /lib/modules/4.4.0-112-generic
toyfish@ubuntown:~$ sudo modprobe l2tp_core
modprobe: FATAL: Module l2tp_core not found in directory /lib/modules/4.4.0-112-generic
toyfish@ubuntown:~$ sudo modprobe l2tp_netlink
modprobe: FATAL: Module l2tp_netlink not found in directory /lib/modules/4.4.0-112-generic
```
:-(

I searched around but didn't find a way to install these modules.

I found a few places recommending something like this: http://blog.z-proj.com/enabling-l2tp-over-ipsec-on-ubuntu-16-04/. This doesn't seem to install the kernel modules tho. I guess it's a different way of supporting l2tp on ubuntu?

**Comment by Juul** [comment]
> I searched around but didn't find a way to install these modules.

To load the modules manually:

```
sudo modprobe l2tp_core
sudo modprobe l2tp_netlink
sudo modprobe l2tp_eth
````

To make them auto-load on each boot add them, one per line, to the file /etc/modules:

```
l2tp_core
l2tp_netlink
l2tp_eth
```

**Comment by bennlich** [comment]
@Juul Repasting error from above:

```
toyfish@ubuntown:~$ sudo modprobe l2tp_eth
modprobe: FATAL: Module l2tp_eth not found in directory /lib/modules/4.4.0-112-generic
toyfish@ubuntown:~$ sudo modprobe l2tp_core
modprobe: FATAL: Module l2tp_core not found in directory /lib/modules/4.4.0-112-generic
toyfish@ubuntown:~$ sudo modprobe l2tp_netlink
modprobe: FATAL: Module l2tp_netlink not found in directory /lib/modules/4.4.0-112-generic
```

Sounds like they're missing, no?

**Comment by Juul** [comment]
```
sudo apt install linux-image-extra-4.4.0-112-generic
```

**Comment by bennlich** [comment]
Woo! Thanks. Worked.

Did you just happen to know that? I was unable to find when searching. I wonder if my search terms were not the best.

**Comment by jhpoelen** [comment]
@bennlich I must have installed this is a mad rush some time ago. I've added to README.md to not forget for future clean installs. Thanks @juul !

**Comment by Juul** [comment]
@bennlich to find out which package contains a file:

First time setting up apt-file:

```
sudo apt install apt-file
sudo apt-file update
```

To search:

```
apt-file search l2tp_eth.ko
```

**Comment by bennlich** [comment]
@Juul omg never used apt-file before amazing!
